model:
        model_type: 'onnx'
        model_path: '/app/autodeploy/artifacts/model.pt.onnx'
        model_file_type: 'onnx'
        version: '1.0.0'
        model_name: 'object detection for bus/trucks'
        endpoint: 'predict'
        protected: 0
        input_type: 'serialized'
        input_shape: [224, 224, 3]
        server:
                name: 'autodeploy'
                port: 8000
input_schema:
        input: 'string'
out_schema:
        out: 'list'
        status: 'int'
preprocess:
        path: 'model_functions'
postprocess:
        path: 'model_functions'
monitor:
        server:
                name: 'rabbitmq'
                port: 5672
        metrics:
                metric1:
                        name: 'KSDrift'
                        reference_data: '/home/kartik/personal_projects/AutoDeploy/structured_ref.npy'
                        type: 'info'
                metric2:
                        name: 'average_per_day'
                        type: 'gauge'
