{
 "title": "Model Monitoring-Initial",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "# Service Metrics\n\nService Metrics allow you to monitor \nhow well the service is performing and track metrics for no. of requests,\naverage data size/req  etc. "
   }
  },
  {
   "title": "API  Endpoint Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status!=\"5xx\"}[30m])) / sum(rate(http_requests_total[30m]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (status) "
    }
   ]
  },
  {
   "title": "Average Request MBs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_size_bytes_sum{handler=\"/predict\"}[30m])) / sum(rate(http_request_size_bytes_count{handler=\"/predict\"}[30m]))"
    }
   ]
  },
  {
   "title": "Average Request Size(MB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_size_bytes_sum{handler=\"/predict\"}[5m])) / sum(rate(http_request_size_bytes_count{handler=\"/predict\"}[5m]))"
    }
   ]
  },
  { "title": "Model Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
   "options": {
    "content": "# Model metrics\n\nModel metrics help to track \nmodel performance and visualize AI exaplainability."
   }
  },
  {
   "title": "Average Confidence",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "model_output_score{} " }
   ]
  },
  {
   "title": "Model Predictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 18 },
   "targets": [
    { "expr": "model_output_score * 100" }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(\n    rate(http_request_duration_seconds_bucket[1m])\n  ) by (le)\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(\n    rate(fastapi_http_request_duration_seconds_bucket[1m])\n  ) by (le)\n)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(\n    rate(fastapi_http_request_duration_seconds_bucket[1m])\n  ) by (le)\n)",
     "legendFormat": "50th percentile"
    }
   ]
  }
 ]
}