apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prediction-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prediction
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
