apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker/docker-compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: monitor
  name: monitor
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    io.kompose.service: monitor
status:
  loadBalancer: {}
