apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker/docker-compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: prediction
  name: prediction
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prediction
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker/docker-compose.yml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: prediction
    spec:
      containers:
        - env:
            - name: CONFIG
              value: /app/
          image: prediction:latest
          name: prediction
          ports:
            - containerPort: 8009
          resources: {}
      restartPolicy: Always
status: {}
