model:
        model_type: 'onnx'
        model_path: ['horse_zebra.onnx', 'horse_zebra.onnx']
        ab_split: [80,20]
        model_file_type: 'onnx'
        version: '1.0.0'
        model_name: 'computer vision classification model.'
        endpoint: 'predict'
        protected: 0
        input_type: 'serialized'
        input_shape: [224, 224, 3]
        server:
                name: 'autodeploy'
                port: 8000
preprocess: 'custom_preprocess_classification'
postprocess: 'custom_postprocess'
input_schema:
        input: 'string'
out_schema:
        out: 'int'
        confidence: 'float'
        status: 'int'
dependency:
        path: '/app/model_dependencies'
monitor:
        server:
                name: 'rabbitmq'
                port: 5672        
        custom_metrics: 'image_brightness'
        metrics:
                average_per_day:
                        type: 'info'
