model:
        model_type: 'sklearn'
        model_path: ['/app/artifacts/logistic_regression_model.pkl', '/app/artifacts/logistic_regression_model.pkl']
        ab_split: [80, 20]
        model_file_type: 'pickle'
        version: '1.0.0'
        model_name: 'scikit-learn iris model'
        endpoint: 'predict'
input_schema:
        age: 'int'
        sex: 'int'
out_schema:
        out: 'int'
        probablity: 'float'
        status: 'int'
server:
        port: 8000
monitor:
        metrics:
                metric1:
                        name: 'KSDrift'
                        reference_data: '/app/artifacts/reference_data.npy'
                        type: 'info'
                metric2:
                        name: 'average_per_day'
                        type: 'gauge'
