model:
        model_type: 'sklearn'
        model_path: ['./logistic_regression_model.pkl', './logistic_regression_model.pkl']
        ab_split: [90, 10]
        model_file_type: 'pickle'
        version: ['2.0.0', '1.0.0']
        model_name: 'scikit-learn iris model'
        endpoint: 'predict'
input_schema:
        age: 'int'
        sex: 'int'
out_schema:
        out: 'int'
        probablity: 'float'
        status: 'int'
server:
        port: 8000
monitor:
        name: 'KSDrift'
        reference_data: './reference_data.npy'
