model:
        model_type: 'sklearn'
        model_path: '/home/kartik/personal_projects/AutoDeploy/autodeploy/logistic_regression_model.pkl'
        model_file_type: 'pickle'
        version: '1.0.0'
        model_name: 'computer vision classification model.'
        endpoint: 'predict'
        protected: 0
        input_type: 'structured'
        server:
                name: 'autodeploy'
                port: 8000
input_schema:
        age: 'int'
        sex: 'int'
out_schema:
        out: 'int'
        probablity: 'float'
        status: 'int'
monitor:
        server:
                name: 'localhost'
                port: 5672
        metrics:
                metric1:
                        name: 'KSDrift'
                        reference_data: '/home/kartik/personal_projects/AutoDeploy/structured_ref.npy'
                        type: 'info'
                metric2:
                        name: 'average_per_day'
                        type: 'gauge'
