model:
        model_type: 'onnx'
        model_path: '/home/kartik/personal_projects/AutoDeploy/horse_zebra.onnx'
        model_file_type: 'onnx'
        version: '1.0.0'
        model_name: 'Onnx computer vision classification model.'
        endpoint: 'predict'
        protected: 0
        type: 'cv'
        input_type: 'url'
cv:
        channels: 3
        input_shape: [224, 224]
        channels_first: 1
        dtype: 'float32'
input_schema:
        input: 'string' 
out_schema:
        out: 'int'
        probablity: 'float'
        status: 'int'
server:
        port: 8000
monitor:
        metrics:
                metric1:
                        name: 'KSDrift'
                        reference_data: './reference_data.npy'
                        type: 'info'
                metric2:
                        name: 'average_per_day'
                        type: 'gauge'
