model:
        model_type: 'onnx'
        model_path: ['/app/artifacts/horse_zebra.onnx', '/app/artifacts/horse_zebra.onnx']
        ab_split: [80,20]
        model_file_type: 'onnx'
        version: '1.0.0'
        model_name: 'Onnx computer vision classification model.'
        endpoint: 'predict'
        protected: 0
        type: 'cv'
        input_type: 'serialized'
cv:
        channels: 3
        input_shape: [224, 224]
        channels_first: 1
        dtype: 'float32'
input_schema:
        input: 'string' 
out_schema:
        out: 'int'
        probablity: 'float'
        status: 'int'
server:
        port: 8000
monitor:
        metrics:
                metric1:
                        name: 'KSDrift'
                        reference_data: '/app/artifacts/reference_data.npy'
                        type: 'info'
                metric2:
                        name: 'average_per_day'
                        type: 'gauge'
